import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from 'next/headers'
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";
import { prisma } from "@/lib/prisma";
import { getUser } from "@/actions/authenticate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const currentUser = await getUser();
  console.log(currentUser)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Navbar user={currentUser}/>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
